name: Mirror to GitLab

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone (needed to push history & tags)

      - name: Push to GitLab
        run: |
          git config --global user.name "Abhishek Kumar"
          git config --global user.email "abhishek.nitdelhi@gmail.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/abhishek_nitdelhi/cv-expert-frontend.git

          # Push only the master branch and tags
          git push gitlab master
          git push gitlab --tags
